site:
  title: Smart Responsor
  url: https://docs.smartresponsor.com
  start_page: ROOT::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: .antora-src

ui:
  bundle:
    url: ./vendor/antora-ui/ui-bundle.zip
  supplemental_files: ./supplemental-ui

antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
      snippet_length: 160
      languages: [en, ru]

urls:
  html_extension_style: indexify

output:
  dir: .site_build
