#!/usr/bin/env python3
from __future__ import annotations
import subprocess
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / '.antora-src'
PAGES_DIR = OUT_DIR / 'modules' / 'ROOT' / 'pages'
NAV_FILE = OUT_DIR / 'modules' / 'ROOT' / 'nav.adoc'
subprocess.run(['python3', str(ROOT / 'tools' / 'build_antora_site_v5.py')], check=True)
for name in ['about','owner','contact','privacy','terms']:
    (PAGES_DIR / name).mkdir(parents=True, exist_ok=True)
(OUT_DIR / 'antora.yml').write_text('name: ROOT\ntitle: Oleksandr Tishchenko\nversion: ~\nnav:\n  - modules/ROOT/nav.adoc\n', encoding='utf-8')
NAV_FILE.write_text('* xref:index.adoc[Home]\n* xref:about/index.adoc[About]\n* xref:owner/index.adoc[Owner]\n* xref:article/index.adoc[Articles]\n* xref:component/index.adoc[Components]\n* xref:manifest/index.adoc[Manifests]\n* xref:contact/index.adoc[Contact]\n* xref:privacy/index.adoc[Privacy]\n* xref:terms/index.adoc[Terms]\n', encoding='utf-8')
(PAGES_DIR / 'index.adoc').write_text('= Oleksandr Tishchenko\n:description: Owner-oriented public portal for Smartresponsor articles, components, manifests, and strategic essays.\n\nThis portal is the current owner-oriented public entry point for *Oleksandr Tishchenko*, *Marketing America Corp*, and *Smartresponsor*.\n\n== What This Portal Covers\n\n* xref:article/index.adoc[Articles] — public essays, technical positioning, and strategic notes.\n* xref:component/index.adoc[Components] — public entry points for ecosystem components.\n* xref:manifest/index.adoc[Manifests] — canon, statements, and owner-level notes.\n* xref:about/index.adoc[About] — what this portal is and how it should be read.\n* xref:owner/index.adoc[Owner] — who stands behind the portal.\n* xref:contact/index.adoc[Contact] — contact scope and owner-controlled contact page.\n\n== Positioning Themes\n\n* AI is a stack, not just a chat interface.\n* AI reveals the quality of thinking.\n* Serious automation should prefer protocol and determinism over human imitation.\n* Commerce is shifting toward agent-ready protocol logic.\n* Execution needs accountability and evidence.\n\n== Selected Reads\n\n* xref:article/ai-is-not-just-chatgpt-five-layer-stack.adoc[AI Is Not Just ChatGPT]\n* xref:article/ai-does-not-replace-thinking-it-reveals-its-quality.adoc[AI Does Not Replace Thinking. It Reveals Its Quality.]\n* xref:article/do-not-scale-the-imitation-of-a-human.adoc[Do Not Scale the Imitation of a Human]\n* xref:article/why-the-next-e-commerce-will-not-be-a-store-with-ai.adoc[Why the Next E-Commerce Will Not Be a Store with AI]\n* xref:article/odyssey-execution-control-plane.adoc[Odyssey: The Execution Control Plane for AI]\n* xref:article/the-first-great-war-between-platforms-and-protocols.adoc[The First Great War Between Platforms and Protocols]\n\n== Owner Anchors\n\n* Oleksandr Tishchenko\n* Marketing America Corp\n* Smartresponsor\n', encoding='utf-8')
(PAGES_DIR / 'about' / 'index.adoc').write_text('= About\n:description: About this owner-oriented public portal and how to read it.\n\nThis site is an owner-oriented public portal built around the work of *Oleksandr Tishchenko*, *Marketing America Corp*, and *Smartresponsor*.\n\nIt serves three purposes:\n\n* as a public article stream,\n* as a map of ecosystem components,\n* as a lightweight public documentation and positioning layer.\n', encoding='utf-8')
(PAGES_DIR / 'owner' / 'index.adoc').write_text('= Owner\n:description: Owner page for Oleksandr Tishchenko and the public context of this portal.\n\nThis portal is currently maintained as an owner-oriented public site.\n\n* Oleksandr Tishchenko\n* Marketing America Corp\n* Smartresponsor\n', encoding='utf-8')
(PAGES_DIR / 'contact' / 'index.adoc').write_text('= Contact\n:description: Contact and inquiry page for Oleksandr Tishchenko, Marketing America Corp, and Smartresponsor.\n\nThis documentation site is currently owner-oriented and maintained by *Oleksandr Tishchenko*.\n\nA dedicated owner-controlled contact block can be placed here.\n', encoding='utf-8')
(PAGES_DIR / 'privacy' / 'index.adoc').write_text('= Privacy\n:description: Privacy policy placeholder for the owner-oriented public portal.\n\nThis section is reserved for the privacy policy of the public documentation portal.\n', encoding='utf-8')
(PAGES_DIR / 'terms' / 'index.adoc').write_text('= Terms\n:description: Terms placeholder for the owner-oriented public portal.\n\nThis section is reserved for the terms and related public legal notices of the documentation portal.\n', encoding='utf-8')
