site_name: Documentation
site_url: https://docs.smartresponsor.com/
repo_url: https://github.com/smartresponsor/documentating
repo_name: smartresponsor/documentating

docs_dir: ../docs
site_dir: ../.site_build

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

plugins:
  - search

nav:
  - Home: index.md
  - Articles: article/index.md
  - Components: component/index.md
